export var SQExprKind;
(function (SQExprKind) {
    SQExprKind[SQExprKind["Entity"] = 0] = "Entity";
    SQExprKind[SQExprKind["SubqueryRef"] = 1] = "SubqueryRef";
    SQExprKind[SQExprKind["ColumnRef"] = 2] = "ColumnRef";
    SQExprKind[SQExprKind["MeasureRef"] = 3] = "MeasureRef";
    SQExprKind[SQExprKind["Aggregation"] = 4] = "Aggregation";
    SQExprKind[SQExprKind["PropertyVariationSource"] = 5] = "PropertyVariationSource";
    SQExprKind[SQExprKind["Hierarchy"] = 6] = "Hierarchy";
    SQExprKind[SQExprKind["HierarchyLevel"] = 7] = "HierarchyLevel";
    SQExprKind[SQExprKind["And"] = 8] = "And";
    SQExprKind[SQExprKind["Between"] = 9] = "Between";
    SQExprKind[SQExprKind["In"] = 10] = "In";
    SQExprKind[SQExprKind["Or"] = 11] = "Or";
    SQExprKind[SQExprKind["Contains"] = 12] = "Contains";
    SQExprKind[SQExprKind["Compare"] = 13] = "Compare";
    SQExprKind[SQExprKind["StartsWith"] = 14] = "StartsWith";
    SQExprKind[SQExprKind["Exists"] = 15] = "Exists";
    SQExprKind[SQExprKind["Not"] = 16] = "Not";
    SQExprKind[SQExprKind["Constant"] = 17] = "Constant";
    SQExprKind[SQExprKind["DateSpan"] = 18] = "DateSpan";
    SQExprKind[SQExprKind["DateAdd"] = 19] = "DateAdd";
    SQExprKind[SQExprKind["Now"] = 20] = "Now";
    SQExprKind[SQExprKind["AnyValue"] = 21] = "AnyValue";
    SQExprKind[SQExprKind["DefaultValue"] = 22] = "DefaultValue";
    SQExprKind[SQExprKind["Arithmetic"] = 23] = "Arithmetic";
    SQExprKind[SQExprKind["FillRule"] = 24] = "FillRule";
    SQExprKind[SQExprKind["ResourcePackageItem"] = 25] = "ResourcePackageItem";
    SQExprKind[SQExprKind["ScopedEval"] = 26] = "ScopedEval";
    SQExprKind[SQExprKind["WithRef"] = 27] = "WithRef";
    SQExprKind[SQExprKind["Percentile"] = 28] = "Percentile";
    SQExprKind[SQExprKind["SelectRef"] = 29] = "SelectRef";
    SQExprKind[SQExprKind["TransformTableRef"] = 30] = "TransformTableRef";
    SQExprKind[SQExprKind["TransformOutputRoleRef"] = 31] = "TransformOutputRoleRef";
    SQExprKind[SQExprKind["ThemeDataColor"] = 32] = "ThemeDataColor";
    SQExprKind[SQExprKind["GroupRef"] = 33] = "GroupRef";
    SQExprKind[SQExprKind["Floor"] = 34] = "Floor";
    SQExprKind[SQExprKind["RoleRef"] = 35] = "RoleRef";
    SQExprKind[SQExprKind["Discretize"] = 36] = "Discretize";
    SQExprKind[SQExprKind["NamedQueryRef"] = 37] = "NamedQueryRef";
    SQExprKind[SQExprKind["Member"] = 38] = "Member";
    SQExprKind[SQExprKind["FilteredEval"] = 39] = "FilteredEval";
    SQExprKind[SQExprKind["Conditional"] = 40] = "Conditional";
})(SQExprKind || (SQExprKind = {}));
export var QueryComparisonKind;
(function (QueryComparisonKind) {
    QueryComparisonKind[QueryComparisonKind["Equal"] = 0] = "Equal";
    QueryComparisonKind[QueryComparisonKind["GreaterThan"] = 1] = "GreaterThan";
    QueryComparisonKind[QueryComparisonKind["GreaterThanOrEqual"] = 2] = "GreaterThanOrEqual";
    QueryComparisonKind[QueryComparisonKind["LessThan"] = 3] = "LessThan";
    QueryComparisonKind[QueryComparisonKind["LessThanOrEqual"] = 4] = "LessThanOrEqual";
    QueryComparisonKind[QueryComparisonKind["Contains"] = 12] = "Contains";
    QueryComparisonKind[QueryComparisonKind["Is"] = 13] = "Is";
    QueryComparisonKind[QueryComparisonKind["StartsWith"] = 14] = "StartsWith";
    QueryComparisonKind[QueryComparisonKind["DoesNotContain"] = 16] = "DoesNotContain";
})(QueryComparisonKind || (QueryComparisonKind = {}));
//# sourceMappingURL=interfaces.js.map